- apps/test-app/app/components/Input.tsx
- apps/test-app/app/routes/submission.aftersubmit.tsx
- apps/test-app/app/routes/submission.notaftersubmit.tsx
- apps/test-app/app/routes/submission.subactions.tsx
- apps/test-app/cypress/integration/submission.ts
- packages/remix-validated-form/src/ValidatedForm.tsx
- packages/remix-validated-form/src/internal/submissionCallbacks.ts
- packages/remix-validated-form/src/validation/types.ts
> Add `subaction` and `resetAfterSubmit` props

- apps/docs/app/components/Checkbox.tsx
- apps/docs/app/components/FormInput.tsx
- apps/docs/app/components/Layout.tsx
- apps/docs/app/examples/checkboxGroups.tsx
- apps/docs/app/routes/arrays-and-nested.mdx
- apps/docs/app/routes/repeated-field-names.mdx
- apps/test-app/app/routes/checkboxes.tsx
- apps/test-app/cypress/integration/checkboxes.ts
- packages/remix-validated-form/src/ValidatedForm.tsx
- packages/remix-validated-form/src/internal/MultiValueMap.ts
- packages/remix-validated-form/src/internal/flatten.ts
> feat: Add support for repeated fields

- README.md
- apps/docs/app/components/Layout.tsx
- apps/docs/app/routes/installation.mdx
- apps/docs/app/routes/zod-form-data/api-reference.mdx
- apps/docs/app/routes/zod-form-data/index.mdx
- apps/test-app/app/routes/zod-form-data.tsx
- apps/test-app/cypress/integration/zod-form-data.ts
- apps/test-app/package.json
- packages/validation-tests/package.json
- packages/validation-tests/tests/util/index.ts
- packages/validation-tests/tests/validation.test.ts
- packages/validation-tests/tests/with-zod.test.ts
- packages/validation-tests/tests/zod-form-data.test.ts
- packages/zod-form-data/README.md
- packages/zod-form-data/package.json
- packages/zod-form-data/src/helpers.ts
- packages/zod-form-data/src/index.ts
- packages/zod-form-data/tsconfig.json
This adds a new library that I'll be publishing called `zod-form-data` designed to ease some of the pain points and hoop jumping of validating FormData with a strict library like `zod`.
---
Resolves #28
> feat: add zod-form-data library

- apps/docs/app/components/Checkbox.tsx
- apps/docs/app/components/CheckboxGroup.tsx
- apps/docs/app/examples/checkboxGroups.tsx
- apps/docs/app/routes/repeated-field-names.mdx
- apps/docs/package.json
- apps/sample-app/app/components/FormInput.tsx
- apps/test-app/app/components/Fieldset.tsx
- apps/test-app/app/components/Input.tsx
- apps/test-app/app/routes/checkboxes.tsx
- apps/test-app/app/routes/default-values.tsx
- apps/test-app/cypress/integration/default-values.ts
- packages/remix-validated-form/src/internal/getInputProps.ts
> feat: handle checkboxes & radios in `getInputProps`

- README.md
- apps/docs/app/examples/checkboxGroups.tsx
- apps/docs/app/examples/demo.tsx
- apps/docs/app/examples/nestedData.tsx
- apps/docs/app/routes/reference/use-field.mdx
- apps/docs/app/routes/reference/use-form-context.mdx
- apps/docs/app/routes/reference/validation-error.mdx
- apps/docs/app/routes/server-validation.mdx
- apps/docs/app/routes/validation-library-support.mdx
- apps/sample-app/app/routes/subjects/$id.edit.tsx
- apps/sample-app/app/routes/subjects/new.tsx
- apps/test-app/app/routes/checkboxes.tsx
- apps/test-app/app/routes/file-input.tsx
- apps/test-app/app/routes/validation-fetcher.tsx
- apps/test-app/app/routes/validation.tsx
- apps/test-app/app/routes/zod-form-data.tsx
- packages/remix-validated-form/src/ValidatedForm.tsx
- packages/remix-validated-form/src/hooks.ts
- packages/remix-validated-form/src/internal/formContext.ts
- packages/remix-validated-form/src/internal/getInputProps.ts
- packages/remix-validated-form/src/validation/createValidator.ts
- packages/remix-validated-form/src/validation/types.ts
- packages/validation-tests/tests/validation.test.ts
- packages/validation-tests/tests/with-zod.test.ts
- packages/with-yup/src/index.ts
- packages/with-zod/src/index.ts
This is especially important for Files, as you need async support to validate image dimensions client side
> Major Update: Async Validation

- apps/docs/app/components/DeprecatedWarning.tsx
- apps/docs/app/routes/reference/use-form-helpers.mdx
- apps/docs/app/routes/reference/use-form-state.mdx
- packages/remix-validated-form/package.json
- packages/remix-validated-form/src/ValidatedForm.tsx
- packages/remix-validated-form/src/hooks.ts
- packages/remix-validated-form/src/internal/getInputProps.ts
- packages/remix-validated-form/src/internal/hooks.ts
- packages/remix-validated-form/src/internal/hydratable.ts
- packages/remix-validated-form/src/internal/logic/getCheckboxChecked.ts
- packages/remix-validated-form/src/internal/logic/getRadioChecked.ts
- packages/remix-validated-form/src/internal/state.ts
- packages/remix-validated-form/src/internal/state/atomUtils.ts
- packages/remix-validated-form/src/internal/util.ts
- packages/remix-validated-form/src/unreleased/formStateHooks.ts
- packages/remix-validated-form/src/userFacingFormContext.ts
- yarn.lock
Also contains a couple small hooks that I'm not releasing yet. Planning on releasing what I have here as a patch that reduces the bundle size.
> refactor: Remove immer as a dependency

- packages/remix-validated-form/src/internal/hooks.ts
> fixed "Unable to determine form" error message

- packages/remix-validated-form/src/server.ts
Adds support to pass headers to `validationError`
> feat: add headers support for validationError

- apps/test-app/app/components/Textarea.tsx
- apps/test-app/app/routes/validation-textarea.tsx
- apps/test-app/app/routes/validation.tsx
- apps/test-app/cypress/integration/validation.ts
- packages/remix-validated-form/src/ValidatedForm.tsx
The textarea element doesn't gain focus when receiving an error.
My small changes (thanks to the author for his help in making this PR):
1. Fixed the validation process so it includes the textarea element
2. Added testing to check if a textarea component receive focus when the form is invalid. Also included a textarea in the test that checks displayed errors.
I'm really a noob in PR, so let me know if I can do anything better.
> Textarea focus

- package.json
- packages/zod-form-data/src/helpers.ts
- packages/zod-form-data/src/zod-form-data.test.ts
- yarn.lock
This PR is for #133
I also went and updated the vitest version to the latest as vscode extension wasn't letting me run it due to the outdate version.
> #133 fix array of objects

- apps/docs/app/examples/defaultValues.tsx
- apps/docs/app/examples/demo.tsx
- apps/docs/app/examples/fieldArray-hook.tsx
- apps/docs/app/routes/integrate-your-components.mdx
- apps/docs/app/routes/reference/validation-error.mdx
- apps/docs/app/routes/server-validation.mdx
- apps/docs/vercel.json
- apps/sample-app/app/components/SubjectForm.tsx
- apps/test-app/app/components/SubmitButton.tsx
- apps/test-app/app/routes/occasional-field-tracking.tsx
- apps/test-app/app/routes/submission.submitter.tsx
- apps/test-app/cypress/integration/controlled-fields.ts
- apps/test-app/cypress/integration/submission.ts
- packages/remix-validated-form/src/ValidatedForm.tsx
- packages/remix-validated-form/src/validation/validation.test.ts
This is the occasional field tracking example as a test case: https://www.remix-validated-form.io/reference/use-control-field
See #123
> Add test case for setting controlled field value on mount

- apps/docs/app/routes/server-validation.mdx
This changes the docs where the closing bracket was misplaced.
> Fix Docs missing closing bracket

- apps/bug-repro/package.json
- apps/docs/package.json
- apps/sample-app/package.json
- apps/test-app/app/routes/file-input.tsx
- apps/test-app/package.json
- packages/remix-validated-form/package.json
- packages/remix-validated-form/src/server.ts
- yarn.lock
> feat: support remix v1.6.5 `TypeResponse`

- apps/test-app/app/routes/context-hooks.tsx
- apps/test-app/cypress/integration/context-hooks.ts
- packages/remix-validated-form/src/internal/state/createFormStore.ts
This one was my bad I don't know why I didn't add any test cases in the first place. 
Closes #148
> fix: fix getValues and add test cases

- apps/docs/app/routes/zod-form-data/index.mdx
`zfd.object` does not exist, the code should be `z.object`
> Fix docs zod-form-data

- packages/with-zod/src/index.ts
> Add ZodTypeDef type bound for TS 4.8.x compatibility

- packages/with-zod/src/index.ts
- packages/with-zod/src/with-zod.test.ts
> Allow passing custom errorMap to withZod

- packages/remix-validated-form/src/ValidatedForm.tsx
This is a (temporary) fix for #172 . This PR really should have some tests added to it, but I was unable to get the test suite working locally, and I unfortunately don't have more time to spend on this at the moment. Totally understand if you want to wait for a proper fix on this.
> Clear form errors on submit

- apps/docs/app/routes/zod-form-data/api-reference.mdx
- apps/test-app/app/routes/submission.aftersubmit.clear-errors.tsx
- apps/test-app/app/routes/submission.external.tsx
- apps/test-app/app/routes/submission.method.tsx
- apps/test-app/cypress/integration/submission.ts
- packages/remix-validated-form/src/ValidatedForm.tsx
- packages/remix-validated-form/src/validation/createValidator.ts
- packages/remix-validated-form/src/validation/validation.test.ts
- packages/zod-form-data/src/helpers.ts
- packages/zod-form-data/src/zod-form-data.test.ts
Fixes #180
Adds test for #179
Closes #174 
Fixes #170 
Fixes #164
> Various fixes

- apps/test-app/app/routes/submission.method.tsx
- apps/test-app/cypress/integration/submission.ts
- packages/remix-validated-form/src/ValidatedForm.tsx
It looks like the method prop is not being passed down to the `fetcher.submit` call in `<ValidatedForm />`. This should fix that.
> fix: pass method to fetcher submit options

- apps/docs/app/components/Alert.tsx
- apps/docs/app/components/Button.tsx
- apps/docs/app/components/Layout.tsx
- apps/docs/styles/index.css
- package.json
Making a PR so I can view a preview deployment.
> feat: add v6 announcement to docs

- packages/core/package.json
- packages/react/package.json
- packages/remix/package.json
- packages/set-get/package.json
- packages/yup/package.json
- packages/zod/package.json
This PR is primarily to make a hard link to issues that are getting closed in v6.
Resolves: #355 
Resolves: #360
Resolves: #354 
Resolves: #351 
Resolves: #341
Resolves: #319
Resolves: #337 
Resolves: #317 
Resolves: #315
Resolves: #312 
Resolves: #311
Resolves: #310
Resolves: #308 
Resolves: #302 
Resolves: #295 
Resolves: #273 
Resolves: #268 
Resolves: #245 
Resolves: #241
Resolves: #218 
Resolves: #207 
Resolves: #104
Resolves: #81
Resolves: #178
Resolves: #206
> Release v6 🎉

- packages/react-router/src/ValidatedForm.tsx
- packages/react-router/src/useForm.tsx
Adding viewTransition as instructed in https://github.com/airjp73/rvf/issues/411. @airjp73 It does not appear to be working when I test it in my code though. I still get the same visual results.
> Adding viewTransition to the useForm
