airjp73/rvf

README.md
apps/docs/app/components/FormInput.tsx
apps/docs/app/components/Layout.tsx
apps/docs/app/components/PropHeader.tsx
apps/docs/app/routes/integrate-your-components.mdx
apps/docs/app/routes/reference/use-field.mdx
apps/docs/app/routes/reference/use-form-context.mdx
apps/docs/package.json
apps/sample-app/app/components/FormInput.tsx
apps/sample-app/app/components/FormSelect.tsx
apps/test-app/app/components/Input.tsx
apps/test-app/app/components/InputWithTouched.tsx
apps/test-app/app/routes/submission.aftersubmit.tsx
apps/test-app/app/routes/submission.hasbeensubmitted.tsx
apps/test-app/app/routes/touched-state.tsx
apps/test-app/app/routes/validation-fetcher.tsx
apps/test-app/app/routes/validation-nofocus.tsx
apps/test-app/app/routes/validation.tsx
apps/test-app/cypress/integration/submission.ts
apps/test-app/cypress/integration/touched-state.ts
apps/test-app/cypress/integration/validation-with-fetchers.ts
apps/test-app/cypress/integration/validation.ts
packages/remix-validated-form/src/ValidatedForm.tsx
packages/remix-validated-form/src/hooks.ts
packages/remix-validated-form/src/internal/formContext.ts
packages/remix-validated-form/src/internal/getInputProps.ts
packages/remix-validated-form/src/validation/types.ts
packages/validation-tests/tests/inputProps.test.ts
yarn.lock

This adds a few small features that culminate in a simpler and more complete experience using `useField`.

feat: encapsulate validation behavior in `getInputProps`

---

README.md

just a simple typo fix on the README example
**PS:** I'm not sure what's the diff on the last line, probably a newline at the end; sorry, doing this edit through GitHub website itself

fix typo on `MyInputProps` example on README

---

packages/zod-form-data/src/helpers.ts

When we use the `formData` function, we don't have a return type like key set on parameters.

fix: zod-form-data `formData` return type not correct

---

packages/zod-form-data/README.md
packages/zod-form-data/src/helpers.ts

This is kind of a weird one, that I just did the implementation of locally and figured could go in here as well.
Would definitely recommend double checking it's use cases, as the whole File thing is a bit dodgy with Remix at the moment :) 
The CustomUploadHandler bit is also a bit different to document, as the dev can realistically convert the File to whatever they want after handling the upload

Add File helpder to `zod-form-data`

---

apps/docs/app/routes/integrate-your-components.mdx

Fix the mismatching interface names:
Includes the import, so it is clear where the `<ValidatedForm>` is coming from

docs: Fix a variable name and includes a missing piece

---

apps/docs/app/routes/reference/use-form-context.mdx

After struggling to understand why the useFormContext hook wasn't working in my project, I've found out it can only be used in ValidatedForm child components, and not at the ValidatedForm component level, which makes sense: context props can only be used by children. That fact that is not clearly stated in the docs is confusing.
This PR:
- Add code example of correct and incorrect usage.

docs: Add usage examples for useFormContext hook

---

apps/docs/app/routes/reference/use-form-context.mdx
packages/remix-validated-form/src/userFacingFormContext.ts

The current subaction was available on the underlying data, but was
not exposed in the type.
Fixes #73

feat: Add subaction as exposed property of FormContext

---

packages/remix-validated-form/package.json

fix #86 
I only updated the peer dependencies version range. I don't have `yarn` setup locally and was running into issues with the project setup, so this is unfortunately all I was able to contribute with the time I had available. Hopefully this helps a bit.
I chose the version range of `^17.0.2 || ^18.0.0` to continue to support React 17  to maintain the package's semver compatibility.

chore: allow installation in React 18 projects

---

packages/vite-config/index.js

This greatly aids debugging the library, since without it stack traces originating in the library are minified. Additionally, bundlers will simply ignore them if the library consumer doesn't want to publish their source, so there's no drawback to including them.

Enable sourceMaps

---

apps/docs/app/routes/async-validation.mdx

Great work on `remix-validated-form`! I noticed a tiny typo and figured I'd open a PR for it.

Fix minor typo in async-validation docs

---

apps/docs/app/examples/defaultValues.tsx
apps/docs/app/examples/demo.tsx
apps/docs/app/examples/nestedData.tsx
apps/docs/app/routes/integrate-your-components.mdx
apps/docs/app/routes/server-validation.mdx
apps/sample-app/app/components/SubjectForm.tsx
packages/remix-validated-form/src/validation/validation.test.ts

Zod has marked string.nonempty as deprecated, and pushes users to use string.min(1) instead.

Docs Zod string.nonempty() → string.min(1)

---

apps/docs/app/routes/reference/use-update-controlled-field.mdx

This links to useControlField, but uses useControlledValue as the link text (an older name for the hook?).

Update useUpdateControlledField documentation

---

apps/test-app/app/routes/file-input.tsx

This is a follow-up PR for fixing the `file-input` Cypess test caused by the https://github.com/airjp73/remix-validated-form/pull/142

Fix `file-input` cypress test

---

packages/zod-form-data/package.json

The license field is missing in package.json for `zod-form-data`.
This means that the correct license is not displayed in npmjs, as well as affecting license scanning dependency tools

Add missing license field to zod-form-data

---

packages/remix-validated-form/package.json
packages/remix-validated-form/src/internal/state/createFormStore.ts

Closes #231 
By the way, 4.6.6 and 4.6.7 don't seem to be published in the repo Release tab.

refactor(zustand): Import named create instead of default

---

packages/zod-form-data/src/helpers.ts

```ts
zfd.formData({
name: zfd.text()
})._input
```
is now of type `FormData` instead of `{ name: string }`.
```ts
const formDataSchema = zfd.formData({
name: zfd.text()
})
const form = formDataSchema.parse(formData)
```
`form` is still typed as `{ name: string }` here.
I need this type to be correct so input types are inferred accurately for a form data integration I'm working on for [tRPC](https://github.com/trpc/trpc/compare/trpc:09634d5...trpc:bea7865#diff-ac3ed79d27fe031890ac3a59f5d04d89d6848ce5dae67f6594d9aff23721e279R95).

fix: input and output types

---

apps/test-app/app/routes/non-object-loader-data.tsx
apps/test-app/cypress/integration/default-values.ts
packages/remix-validated-form/src/internal/hooks.ts

Handle non-object loader data in `useDefaultValuesFromLoader`

---

README.md

This PR fixes a typo in the readme. It also adjusts a few heading types based on markdown lint rules mentioned below.
https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md

Fix: Typo and lint issues in readme

---

packages/remix-validated-form/src/internal/getInputProps.ts

With the compiler option `exactOptionalPropertyTypes` is set to `true` (e.g. when using [@tsconfig/strictest](https://www.npmjs.com/package/@tsconfig/strictest) base config), the type of `getInputProps` can't be inferred correctly.
For example, using the [`Checkbox` component from the docs app](https://github.com/airjp73/remix-validated-form/blob/e6f1855b83b35f0ad27fe19b807855474cf39294/apps/docs/app/components/Checkbox.tsx):
```
Checkbox.tsx:21:49 - error TS2345: Argument of type '{ type: string; value: string | undefined; }' is not assignable to parameter of type 'Omit<MinimalInputProps, HandledProps | Callbacks> & Partial<Pick<MinimalInputProps, Callbacks>>'.
Object literal may only specify known properties, and 'value' does not exist in type 'Omit<MinimalInputProps, HandledProps | …
```

Add explicit `undefined`s to `MinimalInputProps`

---

apps/test-app/package.json
packages/with-yup/package.json
yarn.lock

Yup 1.0 has been released, but cannot be used with remix-validated-form due to version restrictions. This upgrades @remix-validated-form/with-yup to use yup 1.0 or later.

Support yup 1.0

---

packages/remix-validated-form/src/ValidatedForm.tsx

closes #313 
* Adds a `DeepPartial` type
* Uses `DeepPartial` for default types, allowing users to pre-set set a subset of deeply nested fields (useful for [arrays and nested](https://www.remix-validated-form.io/arrays-and-nested) types)
```tsx
// example todo validator
const validator = withZod(
z.array(
z.object({
title: z.string()
dueDate: z.string()
})
)
);
...
<ValidatedForm validator={validator} defaultValues={[{ title: 'my todo' }]}> // Without a `DeepPartial` this causes a type error
// ...
</ValidatedForm>
```
* Updates `DataType` to extend `{ [fieldName: string]: any }` for `ValidatedForm`
* My understanding is that is a requirement anyway, but without explicitly specifying the constraint `DeepPartial` will cause a type error on the `InternalFormContextValue`. This is because …

use `DeepPartial` for acceptable `DataType` into `ValidatedForm`

---

packages/zod-form-data/src/zod-form-data.test.ts

The test case was added to ensure that the zod-form-data library correctly handles validation errors when multiple items fail validation. This helps to improve the reliability and accuracy of the library when dealing with repeatable fields.

test(zod-form-data.test.ts): add test case for failing on multiple items with correct error

---

packages/remix-validated-form/package.json

I wonder how continuing supporting a diverging API will work in the future but for now the library seems to support both v1 and v2.

chore(deps): pin upper remix version to 2

---

apps/bug-repro/package.json
apps/docs/package.json
apps/test-app/package.json
packages/with-zod/package.json
packages/zod-form-data/package.json
packages/zod-form-data/src/zod-form-data.test.ts
yarn.lock

https://github.com/colinhacks/zod/releases/tag/v3.22.3
Fixes #2609
The current regex used for email validation contains "catastrophic backtracking", specifically ([A-Z0-9_+-]+\.?)*. This gets evaluated inefficiently by JS, resulting in an exponential increase in execution time for failed matches.
This can be replicated easily - here's execution time against ^([A-Z0-9_+-]+\.?)*[A-Z0-9_+-]@([A-Z0-9][A-Z0-9\-]*\.)+[A-Z]{2,}$

Update package.json for zod to 3.22.3 or greater

---

apps/docs-v2/app/routes/_docs.recipes.typesafe-input.mdx

This fix solves below browser warning generated when using the current [typesafe input repice ](https://www.rvf-js.io/recipes/typesafe-input#recipe):
```
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
```

docs: fix forwardRef warning for typesafe input recipe

---

packages/core/package.json
packages/react/package.json
packages/zod-form-data/package.json
packages/zod/package.json

If you want to reference `ValidStringPaths` in your code then you get peer dependency warnings once `@rvf/set-get` is installed

Fix peer dependency warning

---

packages/zod-form-data/package.json

Hi, thanks for this package! Looks great.
Currently, the links on [the `zod-form-data` npm package page](https://www.npmjs.com/package/zod-form-data) are as follows:
```
Repository
https://github.com/airjp73/remix-validated-form
Homepage
https://github.com/airjp73/remix-validated-form#readme
```
With this PR, they change as follows:
```
Repository
https://github.com/airjp73/rvf
Homepage
https://github.com/airjp73/rvf/tree/main/packages/zod-form-data
```

Improve npm links

---

apps/docs/app/routes/_docs.reference.form-api.mdx
apps/docs/app/routes/_docs.reference.use-form.mdx
apps/docs/app/routes/_docs.supporting-no-js.mdx
packages/core/src/getters.ts
packages/core/src/store.test.tsx
packages/core/src/store.ts
packages/react/src/array.tsx
packages/react/src/base.tsx
packages/react/src/test/custom-errors.test.tsx
packages/react/src/test/focus.test.tsx
packages/react/src/test/use-native-validity.test.tsx
packages/react/src/useNativeValidity.tsx

I've made a couple breaking-ish tweaks over the last month that I'm finally going to push out.
This also includes an experimental `setCustomError` api on the client side.

unstable_setCustomError and a couple other small improvements

---

apps/docs/app/routes/_docs.input-types.mdx

Fixed a typo in the documentation, correcting "you're schema" to "your schema" in the explanation of expected checkbox values.

Fix docs grammar error
